/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:cbbe5899-95c9-4298-aaf8-c6fa7f682a5b",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_fuwSOSwto",
    "aws_user_pools_web_client_id": "1p90qb5va37vfmcb6hhont879",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://hqhvseaflbfm3fdw3acml3jr2i.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "lex": {
        "botName": "CloudAssistantBot",
        "botId": "SGX90I1XYE",
        "botAliasId": "7HIPZ5RRDP",
        "localeId": "en_US",
        "region": "eu-central-1"
    }
};


export default awsmobile;
